import { DocumentContext } from "@/lib/documents/document-context";
import { parseDocumentHeaderConfig } from "@/domain/document-header-config";
import { MotorEntity } from "@/domain/motor";
import { WorkOrder } from "@/domain/work-order";

const demoOrder: WorkOrder = {
  id: "demo-wo-001",
  companyId: "demo-company",
  number: "НЗ-2026-0142",
  status: "delivered",
  clientId: "demo-client",
  clientName: "Алексей Ким",
  clientPhone: "+7 701 234 56 78",
  vehicleId: "demo-vehicle",
  vehicleLabel: "Hyundai Sonata NF",
  vin: "KMHEF41BP8A123456",
  licensePlate: "A 123 BCD",
  mileage: 184200,
  comment: "Замена двигателя G4KC, диагностика после установки",
  laborLines: [
    {
      id: "l1",
      title: "Снятие и установка двигателя",
      hours: 8,
      unitPrice: 12000,
      assigneeIds: ["emp-1"],
      assigneeRole: "mechanic",
    },
    {
      id: "l2",
      title: "Диагностика и первый запуск",
      hours: 2,
      unitPrice: 8000,
      assigneeIds: ["emp-2"],
      assigneeRole: "diagnostician",
    },
  ],
  partLines: [
    {
      id: "p1",
      itemId: "wh-001",
      source: "warehouse",
      sku: "FLT-OIL-001",
      name: "Масляный фильтр",
      quantity: 1,
      unitPrice: 4200,
      unitCost: 2800,
    },
    {
      id: "p2",
      itemId: "wh-002",
      source: "warehouse",
      sku: "OIL-5W30-4L",
      name: "Масло 5W-30, 4 л",
      quantity: 1,
      unitPrice: 9800,
      unitCost: 6200,
    },
  ],
  motorLines: [],
  pricing: {
    laborTotal: 112000,
    partsTotal: 14000,
    motorsTotal: 0,
    discount: 0,
    grandTotal: 126000,
  },
  createdByUserId: "demo-user",
  createdAt: new Date("2026-06-10T09:00:00"),
  updatedAt: new Date("2026-06-12T17:30:00"),
  confirmedAt: new Date("2026-06-10T10:00:00"),
  completedAt: new Date("2026-06-12T16:00:00"),
  deliveredAt: new Date("2026-06-12T17:30:00"),
};

const demoMotor: MotorEntity = {
  id: "motor-001",
  companyId: "demo-company",
  brandName: "Hyundai",
  engineCode: "G4KC",
  configuration: "2.4 MPI",
  serialCode: "G4KC-88421",
  status: "sold",
  quantity: 1,
  transmission: "AT",
  notes: "184 000 км · контрактный",
  arrivalDate: new Date("2026-02-01"),
  soldDate: new Date("2026-03-14"),
  createdAt: new Date("2026-02-01"),
  updatedAt: new Date("2026-03-14"),
};

export const demoDocumentContext: DocumentContext = {
  company: {
    name: "AutoCore Service",
    legalName: 'ТОО "AutoCore Demo"',
    slogan: "Разборка · СТО · Запчасти",
    address: "г. Алматы, ул. Райымбек 142",
    phone: "+7 727 300 00 00",
    email: "hello@autocore.kz",
    website: "autocore.kz",
    warrantyLabel: "180 дн · 10 000 км",
    warrantyText: "Гарантия распространяется на двигатель при соблюдении регламента обслуживания.",
    primaryColor: "#0a73f2",
    secondaryColor: "#11131a",
    headerConfig: parseDocumentHeaderConfig(undefined, "modern"),
  },
  order: demoOrder,
  orderLabel: demoOrder.number,
  client: {
    id: "demo-client",
    companyId: "demo-company",
    fullName: "Алексей Ким",
    phone: "+7 701 234 56 78",
  },
  vehicle: {
    id: "demo-vehicle",
    companyId: "demo-company",
    clientId: "demo-client",
    make: "Hyundai",
    model: "Sonata NF",
    vin: "KMHEF41BP8A123456",
    licensePlate: "A 123 BCD",
    currentMileage: 184200,
  },
  motors: [demoMotor],
  employees: [
    {
      id: "emp-1",
      uid: "emp-1",
      companyId: "demo-company",
      fullName: "Данияр А.",
      email: "d@demo.kz",
      role: "mechanic",
      permissions: [],
      invitedBy: "demo-user",
      isActive: true,
    },
    {
      id: "emp-2",
      uid: "emp-2",
      companyId: "demo-company",
      fullName: "Сергей М.",
      email: "s@demo.kz",
      role: "mechanic",
      permissions: [],
      invitedBy: "demo-user",
      isActive: true,
    },
  ],
  assigneeNames: new Map([
    ["emp-1", "Данияр А."],
    ["emp-2", "Сергей М."],
  ]),
  vehicleLogbook: [
    {
      workOrderId: "demo-wo-001",
      date: new Date("2026-03-14"),
      mileage: 184200,
      title: "Замена двигателя G4KC",
    },
  ],
  generatedAt: new Date("2026-03-14T17:30:00"),
  locale: "ru-KZ",
  theme: "modern",
};
