#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FUNCTIONS_DIR="${FUNCTIONS_DIR:-$ROOT/firebase/functions}"
ENV_FILE="$FUNCTIONS_DIR/.env"

if [[ ! -d "$FUNCTIONS_DIR" ]]; then
  echo "Functions dir not found: $FUNCTIONS_DIR"
  exit 1
fi

if [[ -n "${STRIPE_SECRET_KEY:-}" ]]; then
  echo "Writing STRIPE_SECRET_KEY to firebase/functions/.env for deploy"
  {
    echo "# Generated by deploy-billing-functions.sh — do not commit"
    echo "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}"
  } > "$ENV_FILE"
else
  if [[ ! -f "$ENV_FILE" ]] || ! grep -q '^STRIPE_SECRET_KEY=.' "$ENV_FILE" 2>/dev/null; then
    echo "Missing STRIPE_SECRET_KEY."
    echo "Run: STRIPE_SECRET_KEY=sk_test_... npm run deploy:billing-functions"
    echo "Or copy firebase/functions/.env.example to firebase/functions/.env"
    exit 1
  fi
fi

echo "Building billing functions in $FUNCTIONS_DIR"
cd "$FUNCTIONS_DIR"
npm install
npm run build

cd "$ROOT"

if ! command -v firebase >/dev/null 2>&1; then
  FIREBASE_BIN="npx -y firebase-tools@latest"
else
  FIREBASE_BIN="firebase"
fi

echo "Deploying billing callables…"
$FIREBASE_BIN deploy --only \
  functions:billing:createMarketingCheckoutSession,\
functions:billing:createCheckoutSession,\
functions:billing:createBillingPortalSession,\
functions:billing:syncCompanyBilling,\
functions:billing:claimMarketingCheckout

echo "Done."
